name: Runtime Tests

# Trigger this when a pull request is merged (which implies pushing to master).
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Run Tests
      run:  make test
    - name: Cleanup
      run: echo rm -rf "${{ github.workspace }}"